MODULE_TOPDIR = ../..

PGM = r.pv

LIBES =  $(GPROJLIB) $(RASTERLIB) $(GISLIB) $(PROJLIB)
DEPENDENCIES = $(GPROJDEP) $(GISDEP)
EXTRA_INC = $(PROJINC)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
